import { NextPage } from 'next';
import { DiagramFigure } from '../../components/DiagramFigure';
import { Station, Train } from '../lib/diagram/types';

const stations: Station[] = [
  { name: '南千歳', strong: true },
  { name: '千歳' },
  { name: '長都' },
  { name: 'サッポロビール庭園' },
  { name: '恵庭' },
  { name: '恵み野' },
  { name: '島松' },
  { name: '北広島', strong: true },
  { name: '上野幌' },
  { name: '新札幌', strong: true },
  { name: '平和' },
  { name: '白石' },
  { name: '苗穂' },
  { name: '札幌', strong: true },
];

const trains: Train[] = [
  {
    name: '1721M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '05:40' },
      { station: '長都', departure: '05:44' },
      { station: 'サッポロビール庭園', departure: '05:46' },
      { station: '恵庭', departure: '05:49' },
      { station: '恵み野', departure: '05:52' },
      { station: '島松', departure: '05:55' },
      { station: '北広島', arrival: '05:59', departure: '06:00' },
      { station: '上野幌', departure: '06:05' },
      { station: '新札幌', departure: '06:09' },
      { station: '平和', departure: '06:12' },
      { station: '白石', departure: '06:15' },
      { station: '苗穂', departure: '06:19' },
      { station: '札幌', arrival: '06:22' },
    ],
  },
  {
    name: '2723M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '05:59' },
      { station: '千歳', departure: '06:03' },
      { station: '長都', departure: '06:06' },
      { station: 'サッポロビール庭園', departure: '06:09' },
      { station: '恵庭', departure: '06:12' },
      { station: '恵み野', departure: '06:14' },
      { station: '島松', departure: '06:17' },
      { station: '北広島', arrival: '06:22', departure: '06:22' },
      { station: '上野幌', departure: '06:28' },
      { station: '新札幌', departure: '06:31' },
      { station: '平和', departure: '06:34' },
      { station: '白石', departure: '06:38' },
      { station: '苗穂', departure: '06:42' },
      { station: '札幌', arrival: '06:45' },
    ],
  },
  {
    name: '2725M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '06:20' },
      { station: '千歳', departure: '06:23' },
      { station: '長都', departure: '06:27' },
      { station: 'サッポロビール庭園', departure: '06:30' },
      { station: '恵庭', departure: '06:32' },
      { station: '恵み野', departure: '06:35' },
      { station: '島松', departure: '06:38' },
      { station: '北広島', arrival: '06:43', departure: '06:43' },
      { station: '上野幌', departure: '06:49' },
      { station: '新札幌', departure: '06:53' },
      { station: '平和', departure: '06:56' },
      { station: '白石', departure: '07:00' },
      { station: '苗穂', departure: '07:04' },
      { station: '札幌', arrival: '07:07' },
    ],
  },
  {
    name: '1001M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '06:38' },
      { station: '千歳', departure: '06:41' },
      { station: '新札幌', departure: '07:01' },
      { station: '札幌', arrival: '07:10' },
    ],
  },
  {
    name: '3821M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '06:42' },
      { station: '千歳', departure: '06:46' },
      { station: '恵庭', departure: '06:52' },
      { station: '北広島', arrival: '06:59', departure: '07:00' },
      { station: '新札幌', departure: '07:08' },
      { station: '白石', departure: '07:13' },
      { station: '札幌', arrival: '07:19' },
    ],
  },
  {
    name: '2727M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '06:48' },
      { station: '千歳', departure: '06:51' },
      { station: '長都', departure: '06:55' },
      { station: '恵庭', departure: '06:59' },
      { station: '恵み野', departure: '07:02' },
      { station: '島松', departure: '07:05' },
      { station: '北広島', arrival: '07:10', departure: '07:10' },
      { station: '上野幌', departure: '07:17' },
      { station: '新札幌', departure: '07:21' },
      { station: '平和', departure: '07:25' },
      { station: '白石', departure: '07:29' },
      { station: '苗穂', departure: '07:34' },
      { station: '札幌', arrival: '07:38' },
    ],
  },
  {
    name: '729M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:00' },
      { station: '千歳', departure: '07:03' },
      { station: '長都', departure: '07:07' },
      { station: '恵庭', departure: '07:10' },
      { station: '恵み野', departure: '07:13' },
      { station: '島松', departure: '07:16' },
      { station: '北広島', arrival: '07:21', departure: '07:21' },
      { station: '上野幌', departure: '07:28' },
      { station: '新札幌', departure: '07:32' },
      { station: '平和', departure: '07:35' },
      { station: '白石', departure: '07:39' },
      { station: '苗穂', departure: '07:44' },
      { station: '札幌', arrival: '07:47' },
    ],
  },
  {
    name: '731M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:07' },
      { station: '千歳', departure: '07:11' },
      { station: '長都', departure: '07:15' },
      { station: 'サッポロビール庭園', departure: '07:18' },
      { station: '恵庭', departure: '07:21' },
      { station: '恵み野', departure: '07:24' },
      { station: '島松', departure: '07:27' },
      { station: '北広島', arrival: '07:31', departure: '07:32' },
      { station: '上野幌', departure: '07:38' },
      { station: '新札幌', departure: '07:42' },
      { station: '平和', departure: '07:46' },
      { station: '白石', departure: '07:51' },
      { station: '苗穂', departure: '07:56' },
      { station: '札幌', arrival: '07:59' },
    ],
  },
  {
    name: '2622D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:13' },
      { station: '千歳', departure: '07:18' },
    ],
  },
  {
    name: '2733M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:20' },
      { station: '千歳', departure: '07:23' },
      { station: '長都', departure: '07:27' },
      { station: '恵庭', departure: '07:31' },
      { station: '恵み野', departure: '07:34' },
      { station: '島松', departure: '07:37' },
      { station: '北広島', arrival: '07:41', departure: '07:42' },
      { station: '上野幌', departure: '07:48' },
      { station: '新札幌', departure: '07:52' },
      { station: '平和', departure: '07:56' },
      { station: '白石', departure: '08:00' },
      { station: '苗穂', departure: '08:05' },
      { station: '札幌', arrival: '08:08' },
    ],
  },
  {
    name: '735M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:25' },
      { station: '千歳', departure: '07:32' },
      { station: '長都', departure: '07:35' },
      { station: '恵庭', departure: '07:40' },
      { station: '恵み野', departure: '07:43' },
      { station: '島松', departure: '07:46' },
      { station: '北広島', arrival: '07:51', departure: '07:51' },
      { station: '上野幌', departure: '07:58' },
      { station: '新札幌', departure: '08:02' },
      { station: '平和', departure: '08:06' },
      { station: '白石', departure: '08:11' },
      { station: '苗穂', departure: '08:16' },
      { station: '札幌', arrival: '08:20' },
    ],
  },
  {
    name: '737M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:36' },
      { station: '千歳', departure: '07:40' },
      { station: '長都', departure: '07:43' },
      { station: '恵庭', departure: '07:48' },
      { station: '恵み野', departure: '07:51' },
      { station: '島松', departure: '07:54' },
      { station: '北広島', arrival: '07:59', departure: '08:00' },
      { station: '上野幌', departure: '08:06' },
      { station: '新札幌', departure: '08:11' },
      { station: '平和', departure: '08:15' },
      { station: '白石', departure: '08:20' },
      { station: '苗穂', departure: '08:26' },
      { station: '札幌', arrival: '08:29' },
    ],
  },
  {
    name: '2739M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:47' },
      { station: '千歳', departure: '07:50' },
      { station: '長都', departure: '07:54' },
      { station: 'サッポロビール庭園', departure: '07:57' },
      { station: '恵庭', departure: '08:00' },
      { station: '恵み野', departure: '08:03' },
      { station: '島松', departure: '08:05' },
      { station: '北広島', arrival: '08:10', departure: '08:11' },
      { station: '上野幌', departure: '08:17' },
      { station: '新札幌', departure: '08:21' },
      { station: '平和', departure: '08:24' },
      { station: '白石', departure: '08:28' },
      { station: '苗穂', departure: '08:32' },
      { station: '札幌', arrival: '08:35' },
    ],
  },
  {
    name: '741M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '07:54' },
      { station: '千歳', departure: '07:58' },
      { station: '長都', departure: '08:02' },
      { station: 'サッポロビール庭園', departure: '08:05' },
      { station: '恵庭', departure: '08:08' },
      { station: '恵み野', departure: '08:10' },
      { station: '島松', departure: '08:13' },
      { station: '北広島', arrival: '08:19', departure: '08:28' },
      { station: '上野幌', departure: '08:34' },
      { station: '新札幌', departure: '08:38' },
      { station: '平和', departure: '08:41' },
      { station: '白石', departure: '08:45' },
      { station: '苗穂', departure: '08:50' },
      { station: '札幌', arrival: '08:53' },
    ],
  },
  {
    name: '1003M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '08:05' },
      { station: '千歳', departure: '08:08' },
      { station: '新札幌', departure: '08:29' },
      { station: '札幌', arrival: '08:38' },
    ],
  },
  {
    name: '3823M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '08:08' },
      { station: '千歳', departure: '08:12' },
      { station: '恵庭', departure: '08:18' },
      { station: '北広島', arrival: '08:25', departure: '08:25' },
      { station: '新札幌', departure: '08:33' },
      { station: '札幌', arrival: '08:42' },
    ],
  },
  {
    name: '1743M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '08:18' },
      { station: '長都', departure: '08:22' },
      { station: 'サッポロビール庭園', departure: '08:25' },
      { station: '恵庭', departure: '08:28' },
      { station: '恵み野', departure: '08:30' },
      { station: '島松', departure: '08:33' },
      { station: '北広島', arrival: '08:38', departure: '08:43' },
      { station: '上野幌', departure: '08:49' },
      { station: '新札幌', departure: '08:53' },
      { station: '平和', departure: '08:56' },
      { station: '白石', departure: '09:04' },
      { station: '苗穂', departure: '09:08' },
      { station: '札幌', arrival: '09:11' },
    ],
  },
  {
    name: '3825M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '08:22' },
      { station: '千歳', departure: '08:26' },
      { station: '恵庭', departure: '08:33' },
      { station: '北広島', arrival: '08:40', departure: '08:41' },
      { station: '新札幌', departure: '08:48' },
      { station: '札幌', arrival: '08:58' },
    ],
  },
  {
    name: '2745M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '08:29' },
      { station: '千歳', departure: '08:33' },
      { station: '長都', departure: '08:36' },
      { station: 'サッポロビール庭園', departure: '08:43' },
      { station: '恵庭', departure: '08:47' },
      { station: '恵み野', departure: '08:50' },
      { station: '島松', departure: '08:53' },
      { station: '北広島', arrival: '08:58', departure: '09:03' },
      { station: '上野幌', departure: '09:10' },
      { station: '新札幌', departure: '09:13' },
      { station: '平和', departure: '09:17' },
      { station: '白石', departure: '09:26' },
      { station: '苗穂', departure: '09:30' },
      { station: '札幌', arrival: '09:34' },
    ],
  },
  {
    name: '3827M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '08:33' },
      { station: '千歳', departure: '08:37' },
      { station: '恵庭', departure: '08:43' },
      { station: '北広島', arrival: '08:50', departure: '08:51' },
      { station: '新札幌', departure: '08:58' },
      { station: '札幌', arrival: '09:07' },
    ],
  },
  {
    name: '2624D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '08:39' },
      { station: '千歳', departure: '08:43' },
    ],
  },
  {
    name: '3829M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '08:44' },
      { station: '千歳', departure: '08:48' },
      { station: '恵庭', departure: '08:53' },
      { station: '北広島', arrival: '09:00', departure: '09:01' },
      { station: '新札幌', departure: '09:09' },
      { station: '札幌', arrival: '09:18' },
    ],
  },
  {
    name: '2747M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '08:48' },
      { station: '千歳', departure: '08:51' },
      { station: '長都', departure: '08:55' },
      { station: 'サッポロビール庭園', departure: '08:57' },
      { station: '恵庭', departure: '09:00' },
      { station: '恵み野', departure: '09:03' },
      { station: '島松', departure: '09:06' },
      { station: '北広島', arrival: '09:11', departure: '09:19' },
      { station: '上野幌', departure: '09:26' },
      { station: '新札幌', departure: '09:29' },
      { station: '平和', departure: '09:33' },
      { station: '白石', departure: '09:40' },
      { station: '苗穂', departure: '09:45' },
      { station: '札幌', arrival: '09:48' },
    ],
  },
  {
    name: '3831M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '08:55' },
      { station: '千歳', departure: '08:59' },
      { station: '恵庭', departure: '09:05' },
      { station: '北広島', arrival: '09:13', departure: '09:13' },
      { station: '新札幌', departure: '09:21' },
      { station: '札幌', arrival: '09:30' },
    ],
  },
  {
    name: '32D',
    type: 'とかち',
    schedules: [
      { station: '南千歳', departure: '09:02' },
      { station: '新札幌', departure: '09:25' },
      { station: '札幌', arrival: '09:34' },
    ],
  },
  {
    name: '1749M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '09:07' },
      { station: '長都', departure: '09:11' },
      { station: '恵庭', departure: '09:14' },
      { station: '恵み野', departure: '09:17' },
      { station: '島松', departure: '09:20' },
      { station: '北広島', arrival: '09:25', departure: '09:34' },
      { station: '上野幌', departure: '09:40' },
      { station: '新札幌', departure: '09:44' },
      { station: '平和', departure: '09:47' },
      { station: '白石', departure: '09:58' },
      { station: '苗穂', departure: '10:03' },
      { station: '札幌', arrival: '10:06' },
    ],
  },
  {
    name: '3833M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '09:09' },
      { station: '千歳', departure: '09:13' },
      { station: '恵庭', departure: '09:19' },
      { station: '北広島', arrival: '09:27', departure: '09:27' },
      { station: '新札幌', departure: '09:35' },
      { station: '札幌', arrival: '09:44' },
    ],
  },
  {
    name: '1D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '09:19' },
      { station: '新札幌', departure: '09:40' },
      { station: '札幌', arrival: '09:50' },
    ],
  },
  {
    name: '3835M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '09:22' },
      { station: '千歳', departure: '09:26' },
      { station: '恵庭', departure: '09:32' },
      { station: '北広島', arrival: '09:39', departure: '09:39' },
      { station: '新札幌', departure: '09:48' },
      { station: '札幌', arrival: '09:57' },
    ],
  },
  {
    name: '3837M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '09:33' },
      { station: '千歳', departure: '09:37' },
      { station: '恵庭', departure: '09:43' },
      { station: '北広島', arrival: '09:50', departure: '09:51' },
      { station: '新札幌', departure: '10:00' },
      { station: '札幌', arrival: '10:09' },
    ],
  },
  {
    name: '1751M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '09:42' },
      { station: '長都', departure: '09:46' },
      { station: 'サッポロビール庭園', departure: '09:48' },
      { station: '恵庭', departure: '09:51' },
      { station: '恵み野', departure: '09:54' },
      { station: '島松', departure: '09:57' },
      { station: '北広島', arrival: '10:02', departure: '10:06' },
      { station: '上野幌', departure: '10:12' },
      { station: '新札幌', departure: '10:16' },
      { station: '平和', departure: '10:19' },
      { station: '白石', departure: '10:23' },
      { station: '苗穂', departure: '10:27' },
      { station: '札幌', arrival: '10:30' },
    ],
  },
  {
    name: '3839M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '09:46' },
      { station: '千歳', departure: '09:50' },
      { station: '恵庭', departure: '09:56' },
      { station: '北広島', arrival: '10:04', departure: '10:04' },
      { station: '新札幌', departure: '10:12' },
      { station: '札幌', arrival: '10:21' },
    ],
  },
  {
    name: '2753M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '09:53' },
      { station: '千歳', departure: '09:56' },
      { station: '長都', departure: '10:00' },
      { station: 'サッポロビール庭園', departure: '10:07' },
      { station: '恵庭', departure: '10:11' },
      { station: '恵み野', departure: '10:15' },
      { station: '島松', departure: '10:18' },
      { station: '北広島', arrival: '10:24', departure: '10:32' },
      { station: '上野幌', departure: '10:48' },
      { station: '新札幌', departure: '10:52' },
      { station: '平和', departure: '10:56' },
      { station: '白石', departure: '11:05' },
      { station: '苗穂', departure: '11:10' },
      { station: '札幌', arrival: '11:13' },
    ],
  },
  {
    name: '3841M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '09:57' },
      { station: '千歳', departure: '10:01' },
      { station: '恵庭', departure: '10:07' },
      { station: '北広島', arrival: '10:15', departure: '10:15' },
      { station: '新札幌', departure: '10:24' },
      { station: '札幌', arrival: '10:33' },
    ],
  },
  {
    name: '3843M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '10:09' },
      { station: '千歳', departure: '10:13' },
      { station: '恵庭', departure: '10:19' },
      { station: '北広島', arrival: '10:26', departure: '10:26' },
      { station: '新札幌', departure: '10:34' },
      { station: '札幌', arrival: '10:44' },
    ],
  },
  {
    name: '4002D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '10:14' },
      { station: '新札幌', departure: '10:38' },
      { station: '札幌', arrival: '10:47' },
    ],
  },
  {
    name: '1005M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '10:19' },
      { station: '千歳', departure: '10:22' },
      { station: '新札幌', departure: '10:44' },
      { station: '札幌', arrival: '10:53' },
    ],
  },
  {
    name: '3845M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '10:22' },
      { station: '千歳', departure: '10:26' },
      { station: '恵庭', departure: '10:32' },
      { station: '北広島', arrival: '10:39', departure: '10:40' },
      { station: '新札幌', departure: '10:48' },
      { station: '札幌', arrival: '10:57' },
    ],
  },
  {
    name: '2755M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '10:26' },
      { station: '千歳', departure: '10:29' },
      { station: '長都', departure: '10:33' },
      { station: 'サッポロビール庭園', departure: '10:35' },
      { station: '恵庭', departure: '10:38' },
      { station: '恵み野', departure: '10:41' },
      { station: '島松', departure: '10:44' },
      { station: '北広島', arrival: '10:49', departure: '10:54' },
      { station: '上野幌', departure: '11:00' },
      { station: '新札幌', departure: '11:04' },
      { station: '平和', departure: '11:07' },
      { station: '白石', departure: '11:16' },
      { station: '苗穂', departure: '11:20' },
      { station: '札幌', arrival: '11:24' },
    ],
  },
  {
    name: '2626D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '10:30' },
      { station: '千歳', departure: '10:34' },
    ],
  },
  {
    name: '3847M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '10:34' },
      { station: '千歳', departure: '10:38' },
      { station: '恵庭', departure: '10:44' },
      { station: '北広島', arrival: '10:51', departure: '10:52' },
      { station: '新札幌', departure: '11:00' },
      { station: '札幌', arrival: '11:09' },
    ],
  },
  {
    name: '1757M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '10:44' },
      { station: '長都', departure: '10:48' },
      { station: 'サッポロビール庭園', departure: '10:55' },
      { station: '恵庭', departure: '10:58' },
      { station: '恵み野', departure: '11:01' },
      { station: '島松', departure: '11:04' },
      { station: '北広島', arrival: '11:09', departure: '11:20' },
      { station: '上野幌', departure: '11:26' },
      { station: '新札幌', departure: '11:30' },
      { station: '平和', departure: '11:33' },
      { station: '白石', departure: '11:41' },
      { station: '苗穂', departure: '11:45' },
      { station: '札幌', arrival: '11:49' },
    ],
  },
  {
    name: '3849M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '10:45' },
      { station: '千歳', departure: '10:49' },
      { station: '恵庭', departure: '10:55' },
      { station: '北広島', arrival: '11:02', departure: '11:02' },
      { station: '新札幌', departure: '11:10' },
      { station: '札幌', arrival: '11:19' },
    ],
  },
  {
    name: '3D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '10:54' },
      { station: '新札幌', departure: '11:18' },
      { station: '札幌', arrival: '11:28' },
    ],
  },
  {
    name: '3851M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '10:57' },
      { station: '千歳', departure: '11:01' },
      { station: '恵庭', departure: '11:07' },
      { station: '北広島', arrival: '11:14', departure: '11:14' },
      { station: '新札幌', departure: '11:22' },
      { station: '札幌', arrival: '11:32' },
    ],
  },
  {
    name: '34D',
    type: 'とかち',
    schedules: [
      { station: '南千歳', departure: '11:02' },
      { station: '新札幌', departure: '11:26' },
      { station: '札幌', arrival: '11:36' },
    ],
  },
  {
    name: '3853M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '11:10' },
      { station: '千歳', departure: '11:14' },
      { station: '恵庭', departure: '11:20' },
      { station: '北広島', arrival: '11:27', departure: '11:28' },
      { station: '新札幌', departure: '11:36' },
      { station: '札幌', arrival: '11:45' },
    ],
  },
  {
    name: '1759M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '11:17' },
      { station: '長都', departure: '11:21' },
      { station: 'サッポロビール庭園', departure: '11:23' },
      { station: '恵庭', departure: '11:26' },
      { station: '恵み野', departure: '11:29' },
      { station: '島松', departure: '11:32' },
      { station: '北広島', arrival: '11:37', departure: '11:42' },
      { station: '上野幌', departure: '11:48' },
      { station: '新札幌', departure: '11:52' },
      { station: '平和', departure: '11:55' },
      { station: '白石', departure: '12:04' },
      { station: '苗穂', departure: '12:09' },
      { station: '札幌', arrival: '12:13' },
    ],
  },
  {
    name: '3855M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '11:21' },
      { station: '千歳', departure: '11:25' },
      { station: '恵庭', departure: '11:32' },
      { station: '北広島', arrival: '11:39', departure: '11:40' },
      { station: '新札幌', departure: '11:48' },
      { station: '札幌', arrival: '11:57' },
    ],
  },
  {
    name: '3857M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '11:33' },
      { station: '千歳', departure: '11:37' },
      { station: '恵庭', departure: '11:43' },
      { station: '北広島', arrival: '11:50', departure: '11:50' },
      { station: '新札幌', departure: '11:58' },
      { station: '札幌', arrival: '12:08' },
    ],
  },
  {
    name: '2761M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '11:38' },
      { station: '千歳', departure: '11:41' },
      { station: '長都', departure: '11:45' },
      { station: '恵庭', departure: '11:49' },
      { station: '恵み野', departure: '11:51' },
      { station: '島松', departure: '11:54' },
      { station: '北広島', arrival: '11:59', departure: '12:08' },
      { station: '上野幌', departure: '12:14' },
      { station: '新札幌', departure: '12:17' },
      { station: '平和', departure: '12:20' },
      { station: '白石', departure: '12:24' },
      { station: '苗穂', departure: '12:28' },
      { station: '札幌', arrival: '12:32' },
    ],
  },
  {
    name: '3859M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '11:45' },
      { station: '千歳', departure: '11:49' },
      { station: '恵庭', departure: '11:55' },
      { station: '北広島', arrival: '12:02', departure: '12:02' },
      { station: '新札幌', departure: '12:10' },
      { station: '札幌', arrival: '12:20' },
    ],
  },
  {
    name: '4004D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '11:51' },
      { station: '新札幌', departure: '12:14' },
      { station: '札幌', arrival: '12:23' },
    ],
  },
  {
    name: '3861M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '11:57' },
      { station: '千歳', departure: '12:01' },
      { station: '恵庭', departure: '12:07' },
      { station: '北広島', arrival: '12:15', departure: '12:15' },
      { station: '新札幌', departure: '12:24' },
      { station: '札幌', arrival: '12:33' },
    ],
  },
  {
    name: '1763M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '12:04' },
      { station: '長都', departure: '12:08' },
      { station: 'サッポロビール庭園', departure: '12:11' },
      { station: '恵庭', departure: '12:14' },
      { station: '恵み野', departure: '12:17' },
      { station: '島松', departure: '12:19' },
      { station: '北広島', arrival: '12:25', departure: '12:34' },
      { station: '上野幌', departure: '12:40' },
      { station: '新札幌', departure: '12:43' },
      { station: '平和', departure: '12:46' },
      { station: '白石', departure: '12:55' },
      { station: '苗穂', departure: '13:00' },
      { station: '札幌', arrival: '13:04' },
    ],
  },
  {
    name: '3863M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '12:11' },
      { station: '千歳', departure: '12:14' },
      { station: '恵庭', departure: '12:20' },
      { station: '北広島', arrival: '12:28', departure: '12:28' },
      { station: '新札幌', departure: '12:36' },
      { station: '札幌', arrival: '12:45' },
    ],
  },
  {
    name: '6005D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '12:16' },
      { station: '新札幌', departure: '12:40' },
      { station: '札幌', arrival: '12:49' },
    ],
  },
  {
    name: '3865M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '12:21' },
      { station: '千歳', departure: '12:25' },
      { station: '恵庭', departure: '12:32' },
      { station: '北広島', arrival: '12:39', departure: '12:40' },
      { station: '新札幌', departure: '12:48' },
      { station: '札幌', arrival: '12:57' },
    ],
  },
  {
    name: '1765M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '12:28' },
      { station: '長都', departure: '12:32' },
      { station: 'サッポロビール庭園', departure: '12:35' },
      { station: '恵庭', departure: '12:37' },
      { station: '恵み野', departure: '12:40' },
      { station: '島松', departure: '12:43' },
      { station: '北広島', arrival: '12:48', departure: '12:54' },
      { station: '上野幌', departure: '13:00' },
      { station: '新札幌', departure: '13:03' },
      { station: '平和', departure: '13:07' },
      { station: '白石', departure: '13:10' },
      { station: '苗穂', departure: '13:15' },
      { station: '札幌', arrival: '13:18' },
    ],
  },
  {
    name: '3867M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '12:33' },
      { station: '千歳', departure: '12:37' },
      { station: '恵庭', departure: '12:43' },
      { station: '北広島', arrival: '12:50', departure: '12:51' },
      { station: '新札幌', departure: '12:59' },
      { station: '札幌', arrival: '13:09' },
    ],
  },
  {
    name: '2767M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '12:37' },
      { station: '千歳', departure: '12:41' },
      { station: '長都', departure: '12:44' },
      { station: 'サッポロビール庭園', departure: '12:47' },
      { station: '恵庭', departure: '12:50' },
      { station: '恵み野', departure: '12:52' },
      { station: '島松', departure: '12:55' },
      { station: '北広島', arrival: '13:00', departure: '13:06' },
      { station: '上野幌', departure: '13:12' },
      { station: '新札幌', departure: '13:16' },
      { station: '平和', departure: '13:19' },
      { station: '白石', departure: '13:28' },
      { station: '苗穂', departure: '13:32' },
      { station: '札幌', arrival: '13:36' },
    ],
  },
  {
    name: '3869M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '12:45' },
      { station: '千歳', departure: '12:49' },
      { station: '恵庭', departure: '12:56' },
      { station: '北広島', arrival: '13:03', departure: '13:04' },
      { station: '新札幌', departure: '13:12' },
      { station: '札幌', arrival: '13:21' },
    ],
  },
  {
    name: '3871M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '12:57' },
      { station: '千歳', departure: '13:01' },
      { station: '恵庭', departure: '13:07' },
      { station: '北広島', arrival: '13:14', departure: '13:14' },
      { station: '新札幌', departure: '13:22' },
      { station: '札幌', arrival: '13:31' },
    ],
  },
  {
    name: '3873M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '13:09' },
      { station: '千歳', departure: '13:13' },
      { station: '恵庭', departure: '13:19' },
      { station: '北広島', arrival: '13:26', departure: '13:26' },
      { station: '新札幌', departure: '13:34' },
      { station: '札幌', arrival: '13:43' },
    ],
  },
  {
    name: '7D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '13:18' },
      { station: '新札幌', departure: '13:42' },
      { station: '札幌', arrival: '13:52' },
    ],
  },
  {
    name: '1769M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '13:16' },
      { station: '長都', departure: '13:19' },
      { station: 'サッポロビール庭園', departure: '13:31' },
      { station: '恵庭', departure: '13:35' },
      { station: '恵み野', departure: '13:37' },
      { station: '島松', departure: '13:44' },
      { station: '北広島', arrival: '13:49', departure: '13:54' },
      { station: '上野幌', departure: '14:00' },
      { station: '新札幌', departure: '14:03' },
      { station: '平和', departure: '14:06' },
      { station: '白石', departure: '14:10' },
      { station: '苗穂', departure: '14:14' },
      { station: '札幌', arrival: '14:17' },
    ],
  },
  {
    name: '3875M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '13:22' },
      { station: '千歳', departure: '13:26' },
      { station: '恵庭', departure: '13:31' },
      { station: '北広島', arrival: '13:38', departure: '13:39' },
      { station: '新札幌', departure: '13:47' },
      { station: '札幌', arrival: '13:56' },
    ],
  },
  {
    name: '36D',
    type: 'とかち',
    schedules: [
      { station: '南千歳', departure: '13:28' },
      { station: '新札幌', departure: '13:54' },
      { station: '札幌', arrival: '14:04' },
    ],
  },
  {
    name: '3877M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '13:33' },
      { station: '千歳', departure: '13:37' },
      { station: '恵庭', departure: '13:44' },
      { station: '北広島', arrival: '13:51', departure: '13:52' },
      { station: '新札幌', departure: '14:00' },
      { station: '札幌', arrival: '14:09' },
    ],
  },
  {
    name: '3879M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '13:45' },
      { station: '千歳', departure: '13:49' },
      { station: '恵庭', departure: '13:56' },
      { station: '北広島', arrival: '14:03', departure: '14:03' },
      { station: '新札幌', departure: '14:11' },
      { station: '札幌', arrival: '14:20' },
    ],
  },
  {
    name: '2628D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '13:53' },
      { station: '千歳', departure: '13:57' },
    ],
  },
  {
    name: '3881M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '13:57' },
      { station: '千歳', departure: '14:01' },
      { station: '恵庭', departure: '14:07' },
      { station: '北広島', arrival: '14:14', departure: '14:14' },
      { station: '新札幌', departure: '14:22' },
      { station: '札幌', arrival: '14:31' },
    ],
  },
  {
    name: '9D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '14:06' },
      { station: '新札幌', departure: '14:28' },
      { station: '札幌', arrival: '14:38' },
    ],
  },
  {
    name: '3883M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '14:09' },
      { station: '千歳', departure: '14:13' },
      { station: '恵庭', departure: '14:19' },
      { station: '北広島', arrival: '14:26', departure: '14:27' },
      { station: '新札幌', departure: '14:35' },
      { station: '札幌', arrival: '14:44' },
    ],
  },
  {
    name: '1771M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '14:16' },
      { station: '長都', departure: '14:20' },
      { station: 'サッポロビール庭園', departure: '14:23' },
      { station: '恵庭', departure: '14:26' },
      { station: '恵み野', departure: '14:29' },
      { station: '島松', departure: '14:31' },
      { station: '北広島', arrival: '14:37', departure: '14:41' },
      { station: '上野幌', departure: '14:48' },
      { station: '新札幌', departure: '14:51' },
      { station: '平和', departure: '14:55' },
      { station: '白石', departure: '14:58' },
      { station: '苗穂', departure: '15:02' },
      { station: '札幌', arrival: '15:06' },
    ],
  },
  {
    name: '2773M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '14:17' },
      { station: '千歳', departure: '14:40' },
      { station: '長都', departure: '14:44' },
      { station: 'サッポロビール庭園', departure: '14:46' },
      { station: '恵庭', departure: '14:49' },
      { station: '恵み野', departure: '14:52' },
      { station: '島松', departure: '14:55' },
      { station: '北広島', arrival: '15:00', departure: '15:04' },
      { station: '上野幌', departure: '15:10' },
      { station: '新札幌', departure: '15:14' },
      { station: '平和', departure: '15:17' },
      { station: '白石', departure: '15:24' },
      { station: '苗穂', departure: '15:28' },
      { station: '札幌', arrival: '15:32' },
    ],
  },
  {
    name: '3885M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '14:21' },
      { station: '千歳', departure: '14:25' },
      { station: '恵庭', departure: '14:32' },
      { station: '北広島', arrival: '14:39', departure: '14:39' },
      { station: '新札幌', departure: '14:47' },
      { station: '札幌', arrival: '14:57' },
    ],
  },
  {
    name: '3887M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '14:33' },
      { station: '千歳', departure: '14:37' },
      { station: '恵庭', departure: '14:43' },
      { station: '北広島', arrival: '14:51', departure: '14:51' },
      { station: '新札幌', departure: '15:00' },
      { station: '札幌', arrival: '15:09' },
    ],
  },
  {
    name: '3889M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '14:45' },
      { station: '千歳', departure: '14:49' },
      { station: '恵庭', departure: '14:55' },
      { station: '北広島', arrival: '15:02', departure: '15:02' },
      { station: '新札幌', departure: '15:10' },
      { station: '札幌', arrival: '15:19' },
    ],
  },
  {
    name: '1007M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '14:53' },
      { station: '千歳', departure: '14:57' },
      { station: '新札幌', departure: '15:18' },
      { station: '札幌', arrival: '15:28' },
    ],
  },
  {
    name: '3891M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '14:57' },
      { station: '千歳', departure: '15:01' },
      { station: '恵庭', departure: '15:07' },
      { station: '北広島', arrival: '15:14', departure: '15:15' },
      { station: '新札幌', departure: '15:24' },
      { station: '札幌', arrival: '15:33' },
    ],
  },
  {
    name: '4006D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '15:03' },
      { station: '新札幌', departure: '15:28' },
      { station: '札幌', arrival: '15:38' },
    ],
  },
  {
    name: '3893M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '15:09' },
      { station: '千歳', departure: '15:13' },
      { station: '恵庭', departure: '15:19' },
      { station: '北広島', arrival: '15:26', departure: '15:26' },
      { station: '新札幌', departure: '15:34' },
      { station: '札幌', arrival: '15:43' },
    ],
  },
  {
    name: '2775M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '15:13' },
      { station: '千歳', departure: '15:17' },
      { station: '長都', departure: '15:20' },
      { station: 'サッポロビール庭園', departure: '15:23' },
      { station: '恵庭', departure: '15:26' },
      { station: '恵み野', departure: '15:28' },
      { station: '島松', departure: '15:31' },
      { station: '北広島', arrival: '15:36', departure: '15:41' },
      { station: '上野幌', departure: '15:47' },
      { station: '新札幌', departure: '15:50' },
      { station: '平和', departure: '15:53' },
      { station: '白石', departure: '15:56' },
      { station: '苗穂', departure: '16:01' },
      { station: '札幌', arrival: '16:04' },
    ],
  },
  {
    name: '3895M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '15:21' },
      { station: '千歳', departure: '15:25' },
      { station: '恵庭', departure: '15:31' },
      { station: '北広島', arrival: '15:38', departure: '15:39' },
      { station: '新札幌', departure: '15:46' },
      { station: '札幌', arrival: '15:57' },
    ],
  },
  {
    name: '11D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '15:30' },
      { station: '新札幌', departure: '15:55' },
      { station: '札幌', arrival: '16:04' },
    ],
  },
  {
    name: '1777M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '15:28' },
      { station: '長都', departure: '15:32' },
      { station: 'サッポロビール庭園', departure: '15:43' },
      { station: '恵庭', departure: '15:47' },
      { station: '恵み野', departure: '15:50' },
      { station: '島松', departure: '15:53' },
      { station: '北広島', arrival: '15:58', departure: '16:09' },
      { station: '上野幌', departure: '16:15' },
      { station: '新札幌', departure: '16:18' },
      { station: '平和', departure: '16:21' },
      { station: '白石', departure: '16:25' },
      { station: '苗穂', departure: '16:29' },
      { station: '札幌', arrival: '16:33' },
    ],
  },
  {
    name: '3897M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '15:33' },
      { station: '千歳', departure: '15:37' },
      { station: '恵庭', departure: '15:43' },
      { station: '北広島', arrival: '15:50', departure: '15:50' },
      { station: '新札幌', departure: '15:59' },
      { station: '札幌', arrival: '16:08' },
    ],
  },
  {
    name: '1779M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '15:44' },
      { station: '長都', departure: '15:48' },
      { station: 'サッポロビール庭園', departure: '15:58' },
      { station: '恵庭', departure: '16:02' },
      { station: '恵み野', departure: '16:05' },
      { station: '島松', departure: '16:07' },
      { station: '北広島', arrival: '16:13', departure: '16:19' },
      { station: '上野幌', departure: '16:26' },
      { station: '新札幌', departure: '16:30' },
      { station: '平和', departure: '16:33' },
      { station: '白石', departure: '16:43' },
      { station: '苗穂', departure: '16:48' },
      { station: '札幌', arrival: '16:51' },
    ],
  },
  {
    name: '3899M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '15:45' },
      { station: '千歳', departure: '15:49' },
      { station: '恵庭', departure: '15:55' },
      { station: '北広島', arrival: '16:02', departure: '16:02' },
      { station: '新札幌', departure: '16:11' },
      { station: '札幌', arrival: '16:20' },
    ],
  },
  {
    name: '38D',
    type: 'とかち',
    schedules: [
      { station: '南千歳', departure: '15:51' },
      { station: '新札幌', departure: '16:14' },
      { station: '札幌', arrival: '16:23' },
    ],
  },
  {
    name: '3911M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '15:57' },
      { station: '千歳', departure: '16:01' },
      { station: '恵庭', departure: '16:07' },
      { station: '北広島', arrival: '16:15', departure: '16:16' },
      { station: '新札幌', departure: '16:24' },
      { station: '札幌', arrival: '16:33' },
    ],
  },
  {
    name: '3913M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '16:09' },
      { station: '千歳', departure: '16:13' },
      { station: '恵庭', departure: '16:19' },
      { station: '北広島', arrival: '16:26', departure: '16:27' },
      { station: '新札幌', departure: '16:35' },
      { station: '札幌', arrival: '16:45' },
    ],
  },
  {
    name: '2781M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '16:13' },
      { station: '千歳', departure: '16:16' },
      { station: '長都', departure: '16:20' },
      { station: 'サッポロビール庭園', departure: '16:23' },
      { station: '恵庭', departure: '16:25' },
      { station: '恵み野', departure: '16:28' },
      { station: '島松', departure: '16:31' },
      { station: '北広島', arrival: '16:36', departure: '16:44' },
      { station: '上野幌', departure: '16:50' },
      { station: '新札幌', departure: '16:54' },
      { station: '平和', departure: '16:57' },
      { station: '白石', departure: '17:05' },
      { station: '苗穂', departure: '17:09' },
      { station: '札幌', arrival: '17:13' },
    ],
  },
  {
    name: '3915M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '16:21' },
      { station: '千歳', departure: '16:25' },
      { station: '恵庭', departure: '16:31' },
      { station: '北広島', arrival: '16:38', departure: '16:38' },
      { station: '新札幌', departure: '16:47' },
      { station: '札幌', arrival: '16:56' },
    ],
  },
  {
    name: '3917M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '16:33' },
      { station: '千歳', departure: '16:37' },
      { station: '恵庭', departure: '16:43' },
      { station: '北広島', arrival: '16:50', departure: '16:50' },
      { station: '新札幌', departure: '16:59' },
      { station: '札幌', arrival: '17:08' },
    ],
  },
  {
    name: '1783M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '16:40' },
      { station: '長都', departure: '16:44' },
      { station: 'サッポロビール庭園', departure: '16:47' },
      { station: '恵庭', departure: '16:50' },
      { station: '恵み野', departure: '16:53' },
      { station: '島松', departure: '16:56' },
      { station: '北広島', arrival: '17:01', departure: '17:05' },
      { station: '上野幌', departure: '17:12' },
      { station: '新札幌', departure: '17:15' },
      { station: '平和', departure: '17:18' },
      { station: '白石', departure: '17:33' },
      { station: '苗穂', departure: '17:38' },
      { station: '札幌', arrival: '17:41' },
    ],
  },
  {
    name: '3919M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '16:45' },
      { station: '千歳', departure: '16:49' },
      { station: '恵庭', departure: '16:55' },
      { station: '北広島', arrival: '17:03', departure: '17:03' },
      { station: '新札幌', departure: '17:12' },
      { station: '札幌', arrival: '17:21' },
    ],
  },
  {
    name: '13D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '16:53' },
      { station: '新札幌', departure: '17:20' },
      { station: '札幌', arrival: '17:30' },
    ],
  },
  {
    name: '3921M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '16:57' },
      { station: '千歳', departure: '17:01' },
      { station: '恵庭', departure: '17:07' },
      { station: '北広島', arrival: '17:14', departure: '17:14' },
      { station: '新札幌', departure: '17:23' },
      { station: '札幌', arrival: '17:33' },
    ],
  },
  {
    name: '1785M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '17:04' },
      { station: '長都', departure: '17:08' },
      { station: 'サッポロビール庭園', departure: '17:10' },
      { station: '恵庭', departure: '17:13' },
      { station: '恵み野', departure: '17:16' },
      { station: '島松', departure: '17:19' },
      { station: '北広島', arrival: '17:24', departure: '17:30' },
      { station: '上野幌', departure: '17:37' },
      { station: '新札幌', departure: '17:40' },
      { station: '平和', departure: '17:43' },
      { station: '白石', departure: '17:47' },
      { station: '苗穂', departure: '17:51' },
      { station: '札幌', arrival: '17:54' },
    ],
  },
  {
    name: '2630D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '17:04' },
      { station: '千歳', departure: '17:09' },
    ],
  },
  {
    name: '3923M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '17:09' },
      { station: '千歳', departure: '17:13' },
      { station: '恵庭', departure: '17:19' },
      { station: '北広島', arrival: '17:26', departure: '17:26' },
      { station: '新札幌', departure: '17:34' },
      { station: '札幌', arrival: '17:44' },
    ],
  },
  {
    name: '2787M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '17:14' },
      { station: '千歳', departure: '17:17' },
      { station: '長都', departure: '17:20' },
      { station: 'サッポロビール庭園', departure: '17:23' },
      { station: '恵庭', departure: '17:26' },
      { station: '恵み野', departure: '17:29' },
      { station: '島松', departure: '17:31' },
      { station: '北広島', arrival: '17:36', departure: '17:41' },
      { station: '上野幌', departure: '17:58' },
      { station: '新札幌', departure: '18:02' },
      { station: '平和', departure: '18:05' },
      { station: '白石', departure: '18:08' },
      { station: '苗穂', departure: '18:13' },
      { station: '札幌', arrival: '18:16' },
    ],
  },
  {
    name: '3925M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '17:21' },
      { station: '千歳', departure: '17:25' },
      { station: '恵庭', departure: '17:31' },
      { station: '北広島', arrival: '17:38', departure: '17:39' },
      { station: '新札幌', departure: '17:48' },
      { station: '札幌', arrival: '17:57' },
    ],
  },
  {
    name: '4008D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '17:29' },
      { station: '新札幌', departure: '17:54' },
      { station: '札幌', arrival: '18:03' },
    ],
  },
  {
    name: '3927M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '17:33' },
      { station: '千歳', departure: '17:37' },
      { station: '恵庭', departure: '17:43' },
      { station: '北広島', arrival: '17:50', departure: '17:50' },
      { station: '新札幌', departure: '17:58' },
      { station: '札幌', arrival: '18:07' },
    ],
  },
  {
    name: '1789M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '17:40' },
      { station: '長都', departure: '17:44' },
      { station: '恵庭', departure: '17:48' },
      { station: '恵み野', departure: '17:51' },
      { station: '島松', departure: '17:53' },
      { station: '北広島', arrival: '17:58', departure: '18:06' },
      { station: '上野幌', departure: '18:12' },
      { station: '新札幌', departure: '18:15' },
      { station: '平和', departure: '18:19' },
      { station: '白石', departure: '18:23' },
      { station: '苗穂', departure: '18:27' },
      { station: '札幌', arrival: '18:31' },
    ],
  },
  {
    name: '1009M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '17:43' },
      { station: '千歳', departure: '17:46' },
      { station: '新札幌', departure: '18:07' },
      { station: '札幌', arrival: '18:16' },
    ],
  },
  {
    name: '3929M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '17:46' },
      { station: '千歳', departure: '17:50' },
      { station: '恵庭', departure: '17:56' },
      { station: '北広島', arrival: '18:03', departure: '18:04' },
      { station: '新札幌', departure: '18:12' },
      { station: '札幌', arrival: '18:21' },
    ],
  },
  {
    name: '2791M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '17:51' },
      { station: '千歳', departure: '17:54' },
      { station: '長都', departure: '17:57' },
      { station: 'サッポロビール庭園', departure: '18:00' },
      { station: '恵庭', departure: '18:03' },
      { station: '恵み野', departure: '18:06' },
      { station: '島松', departure: '18:08' },
      { station: '北広島', arrival: '18:13', departure: '18:18' },
      { station: '上野幌', departure: '18:25' },
      { station: '新札幌', departure: '18:28' },
      { station: '平和', departure: '18:31' },
      { station: '白石', departure: '18:45' },
      { station: '苗穂', departure: '18:50' },
      { station: '札幌', arrival: '18:53' },
    ],
  },
  {
    name: '3931M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '17:57' },
      { station: '千歳', departure: '18:01' },
      { station: '恵庭', departure: '18:08' },
      { station: '北広島', arrival: '18:15', departure: '18:16' },
      { station: '新札幌', departure: '18:24' },
      { station: '札幌', arrival: '18:33' },
    ],
  },
  {
    name: '1793M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '18:08' },
      { station: '長都', departure: '18:12' },
      { station: 'サッポロビール庭園', departure: '18:22' },
      { station: '恵庭', departure: '18:25' },
      { station: '恵み野', departure: '18:28' },
      { station: '島松', departure: '18:31' },
      { station: '北広島', arrival: '18:36', departure: '18:41' },
      { station: '上野幌', departure: '18:47' },
      { station: '新札幌', departure: '18:50' },
      { station: '平和', departure: '18:53' },
      { station: '白石', departure: '18:57' },
      { station: '苗穂', departure: '19:01' },
      { station: '札幌', arrival: '19:04' },
    ],
  },
  {
    name: '3933M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '18:09' },
      { station: '千歳', departure: '18:13' },
      { station: '恵庭', departure: '18:19' },
      { station: '北広島', arrival: '18:26', departure: '18:26' },
      { station: '新札幌', departure: '18:35' },
      { station: '札幌', arrival: '18:44' },
    ],
  },
  {
    name: '15D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '18:16' },
      { station: '新札幌', departure: '18:39' },
      { station: '札幌', arrival: '18:47' },
    ],
  },
  {
    name: '3935M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '18:21' },
      { station: '千歳', departure: '18:25' },
      { station: '恵庭', departure: '18:31' },
      { station: '北広島', arrival: '18:38', departure: '18:38' },
      { station: '新札幌', departure: '18:47' },
      { station: '札幌', arrival: '18:57' },
    ],
  },
  {
    name: '3937M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '18:33' },
      { station: '千歳', departure: '18:37' },
      { station: '恵庭', departure: '18:43' },
      { station: '北広島', arrival: '18:50', departure: '18:50' },
      { station: '新札幌', departure: '18:59' },
      { station: '札幌', arrival: '19:09' },
    ],
  },
  {
    name: '1795M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '18:44' },
      { station: '長都', departure: '18:48' },
      { station: 'サッポロビール庭園', departure: '18:56' },
      { station: '恵庭', departure: '18:59' },
      { station: '恵み野', departure: '19:02' },
      { station: '島松', departure: '19:05' },
      { station: '北広島', arrival: '19:10', departure: '19:18' },
      { station: '上野幌', departure: '19:24' },
      { station: '新札幌', departure: '19:28' },
      { station: '平和', departure: '19:31' },
      { station: '白石', departure: '19:35' },
      { station: '苗穂', departure: '19:39' },
      { station: '札幌', arrival: '19:43' },
    ],
  },
  {
    name: '3939M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '18:45' },
      { station: '千歳', departure: '18:49' },
      { station: '恵庭', departure: '18:55' },
      { station: '北広島', arrival: '19:02', departure: '19:03' },
      { station: '新札幌', departure: '19:11' },
      { station: '札幌', arrival: '19:20' },
    ],
  },
  {
    name: '3941M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '18:58' },
      { station: '千歳', departure: '19:01' },
      { station: '恵庭', departure: '19:07' },
      { station: '北広島', arrival: '19:15', departure: '19:15' },
      { station: '新札幌', departure: '19:24' },
      { station: '札幌', arrival: '19:33' },
    ],
  },
  {
    name: '2797M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '19:02' },
      { station: '千歳', departure: '19:05' },
      { station: '長都', departure: '19:09' },
      { station: 'サッポロビール庭園', departure: '19:11' },
      { station: '恵庭', departure: '19:14' },
      { station: '恵み野', departure: '19:17' },
      { station: '島松', departure: '19:20' },
      { station: '北広島', arrival: '19:25', departure: '19:29' },
      { station: '上野幌', departure: '19:36' },
      { station: '新札幌', departure: '19:39' },
      { station: '平和', departure: '19:43' },
      { station: '白石', departure: '19:55' },
      { station: '苗穂', departure: '19:59' },
      { station: '札幌', arrival: '20:03' },
    ],
  },
  {
    name: '3943M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '19:10' },
      { station: '千歳', departure: '19:14' },
      { station: '恵庭', departure: '19:20' },
      { station: '北広島', arrival: '19:27', departure: '19:27' },
      { station: '新札幌', departure: '19:36' },
      { station: '札幌', arrival: '19:45' },
    ],
  },
  {
    name: '3945M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '19:21' },
      { station: '千歳', departure: '19:25' },
      { station: '恵庭', departure: '19:31' },
      { station: '北広島', arrival: '19:38', departure: '19:38' },
      { station: '新札幌', departure: '19:46' },
      { station: '札幌', arrival: '19:55' },
    ],
  },
  {
    name: '1011M',
    type: 'すずらん',
    schedules: [
      { station: '南千歳', departure: '19:25' },
      { station: '千歳', departure: '19:28' },
      { station: '新札幌', departure: '19:50' },
      { station: '札幌', arrival: '19:58' },
    ],
  },
  {
    name: '3947M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '19:33' },
      { station: '千歳', departure: '19:37' },
      { station: '恵庭', departure: '19:43' },
      { station: '北広島', arrival: '19:50', departure: '19:50' },
      { station: '新札幌', departure: '19:59' },
      { station: '札幌', arrival: '20:08' },
    ],
  },
  {
    name: '1799M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '19:40' },
      { station: '長都', departure: '19:44' },
      { station: 'サッポロビール庭園', departure: '19:47' },
      { station: '恵庭', departure: '19:49' },
      { station: '恵み野', departure: '19:52' },
      { station: '島松', departure: '19:55' },
      { station: '北広島', arrival: '20:00', departure: '20:05' },
      { station: '上野幌', departure: '20:11' },
      { station: '新札幌', departure: '20:14' },
      { station: '平和', departure: '20:17' },
      { station: '白石', departure: '20:32' },
      { station: '苗穂', departure: '20:36' },
      { station: '札幌', arrival: '20:40' },
    ],
  },
  {
    name: '2632D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '19:40' },
      { station: '千歳', departure: '19:45' },
    ],
  },
  {
    name: '3949M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '19:45' },
      { station: '千歳', departure: '19:49' },
      { station: '恵庭', departure: '19:55' },
      { station: '北広島', arrival: '20:02', departure: '20:02' },
      { station: '新札幌', departure: '20:11' },
      { station: '札幌', arrival: '20:20' },
    ],
  },
  {
    name: '2811M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '19:49' },
      { station: '千歳', departure: '19:53' },
      { station: '長都', departure: '19:56' },
      { station: 'サッポロビール庭園', departure: '20:11' },
      { station: '恵庭', departure: '20:14' },
      { station: '恵み野', departure: '20:17' },
      { station: '島松', departure: '20:19' },
      { station: '北広島', arrival: '20:24', departure: '20:29' },
      { station: '上野幌', departure: '20:36' },
      { station: '新札幌', departure: '20:39' },
      { station: '平和', departure: '20:42' },
      { station: '白石', departure: '20:46' },
      { station: '苗穂', departure: '20:50' },
      { station: '札幌', arrival: '20:53' },
    ],
  },
  {
    name: '4010D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '19:54' },
      { station: '新札幌', departure: '20:19' },
      { station: '札幌', arrival: '20:28' },
    ],
  },
  {
    name: '3951M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '19:57' },
      { station: '千歳', departure: '20:01' },
      { station: '恵庭', departure: '20:07' },
      { station: '北広島', arrival: '20:14', departure: '20:14' },
      { station: '新札幌', departure: '20:23' },
      { station: '札幌', arrival: '20:32' },
    ],
  },
  {
    name: '17D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '20:03' },
      { station: '新札幌', departure: '20:26' },
      { station: '札幌', arrival: '20:35' },
    ],
  },
  {
    name: '3953M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '20:09' },
      { station: '千歳', departure: '20:13' },
      { station: '恵庭', departure: '20:19' },
      { station: '北広島', arrival: '20:26', departure: '20:27' },
      { station: '新札幌', departure: '20:35' },
      { station: '札幌', arrival: '20:44' },
    ],
  },
  {
    name: '1813M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '20:19' },
      { station: '長都', departure: '20:23' },
      { station: 'サッポロビール庭園', departure: '20:25' },
      { station: '恵庭', departure: '20:28' },
      { station: '恵み野', departure: '20:31' },
      { station: '島松', departure: '20:34' },
      { station: '北広島', arrival: '20:39', departure: '20:44' },
      { station: '上野幌', departure: '20:50' },
      { station: '新札幌', departure: '20:53' },
      { station: '平和', departure: '20:56' },
      { station: '白石', departure: '21:00' },
      { station: '苗穂', departure: '21:04' },
      { station: '札幌', arrival: '21:08' },
    ],
  },
  {
    name: '3955M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '20:23' },
      { station: '千歳', departure: '20:27' },
      { station: '恵庭', departure: '20:33' },
      { station: '北広島', arrival: '20:41', departure: '20:41' },
      { station: '新札幌', departure: '20:49' },
      { station: '札幌', arrival: '20:58' },
    ],
  },
  {
    name: '3957M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '20:35' },
      { station: '千歳', departure: '20:39' },
      { station: '恵庭', departure: '20:45' },
      { station: '北広島', arrival: '20:52', departure: '20:52' },
      { station: '新札幌', departure: '21:01' },
      { station: '白石', departure: '21:06' },
      { station: '札幌', arrival: '21:12' },
    ],
  },
  {
    name: '2815M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '20:44' },
      { station: '千歳', departure: '20:47' },
      { station: '長都', departure: '20:51' },
      { station: 'サッポロビール庭園', departure: '20:58' },
      { station: '恵庭', departure: '21:01' },
      { station: '恵み野', departure: '21:04' },
      { station: '島松', departure: '21:07' },
      { station: '北広島', arrival: '21:12', departure: '21:21' },
      { station: '上野幌', departure: '21:27' },
      { station: '新札幌', departure: '21:31' },
      { station: '平和', departure: '21:34' },
      { station: '白石', departure: '21:38' },
      { station: '苗穂', departure: '21:42' },
      { station: '札幌', arrival: '21:45' },
    ],
  },
  {
    name: '4959M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '20:50' },
      { station: '新札幌', departure: '21:13' },
      { station: '札幌', arrival: '21:22' },
    ],
  },
  {
    name: '3961M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '20:55' },
      { station: '千歳', departure: '20:59' },
      { station: '恵庭', departure: '21:06' },
      { station: '北広島', arrival: '21:14', departure: '21:15' },
      { station: '新札幌', departure: '21:23' },
      { station: '白石', departure: '21:28' },
      { station: '札幌', arrival: '21:34' },
    ],
  },
  {
    name: '19D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '21:06' },
      { station: '新札幌', departure: '21:27' },
      { station: '札幌', arrival: '21:37' },
    ],
  },
  {
    name: '3963M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '21:11' },
      { station: '千歳', departure: '21:15' },
      { station: '恵庭', departure: '21:21' },
      { station: '北広島', arrival: '21:28', departure: '21:28' },
      { station: '新札幌', departure: '21:36' },
      { station: '白石', departure: '21:42' },
      { station: '札幌', arrival: '21:48' },
    ],
  },
  {
    name: '3965M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '21:24' },
      { station: '千歳', departure: '21:28' },
      { station: '恵庭', departure: '21:33' },
      { station: '北広島', arrival: '21:40', departure: '21:41' },
      { station: '新札幌', departure: '21:50' },
      { station: '白石', departure: '21:55' },
      { station: '札幌', arrival: '22:01' },
    ],
  },
  {
    name: '2817M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '21:30' },
      { station: '千歳', departure: '21:33' },
      { station: '長都', departure: '21:37' },
      { station: 'サッポロビール庭園', departure: '21:48' },
      { station: '恵庭', departure: '21:52' },
      { station: '恵み野', departure: '21:55' },
      { station: '島松', departure: '21:57' },
      { station: '北広島', arrival: '22:03', departure: '22:08' },
      { station: '上野幌', departure: '22:14' },
      { station: '新札幌', departure: '22:17' },
      { station: '平和', departure: '22:20' },
      { station: '白石', departure: '22:28' },
      { station: '苗穂', departure: '22:32' },
      { station: '札幌', arrival: '22:35' },
    ],
  },
  {
    name: '3967M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '21:34' },
      { station: '千歳', departure: '21:38' },
      { station: '恵庭', departure: '21:44' },
      { station: '北広島', arrival: '21:51', departure: '21:51' },
      { station: '新札幌', departure: '22:00' },
      { station: '白石', departure: '22:06' },
      { station: '札幌', arrival: '22:12' },
    ],
  },
  {
    name: '40D',
    type: 'とかち',
    schedules: [
      { station: '南千歳', departure: '21:40' },
      { station: '新札幌', departure: '22:05' },
      { station: '札幌', arrival: '22:15' },
    ],
  },
  {
    name: '3969M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '21:48' },
      { station: '千歳', departure: '21:52' },
      { station: '恵庭', departure: '21:57' },
      { station: '北広島', arrival: '22:05', departure: '22:05' },
      { station: '新札幌', departure: '22:14' },
      { station: '白石', departure: '22:19' },
      { station: '札幌', arrival: '22:25' },
    ],
  },
  {
    name: '2819D',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '21:54' },
      { station: '千歳', departure: '22:04' },
      { station: '長都', departure: '22:08' },
      { station: 'サッポロビール庭園', departure: '22:19' },
      { station: '恵庭', departure: '22:22' },
      { station: '恵み野', departure: '22:26' },
      { station: '島松', departure: '22:29' },
      { station: '北広島', arrival: '22:35', departure: '22:44' },
      { station: '上野幌', departure: '22:51' },
      { station: '新札幌', departure: '22:55' },
      { station: '平和', departure: '22:59' },
      { station: '白石', departure: '23:03' },
      { station: '苗穂', departure: '23:08' },
      { station: '札幌', arrival: '23:11' },
    ],
  },
  {
    name: '4971M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '21:59' },
      { station: '新札幌', departure: '22:22' },
      { station: '札幌', arrival: '22:31' },
    ],
  },
  {
    name: '21D',
    type: '北斗',
    schedules: [
      { station: '南千歳', departure: '22:06' },
      { station: '新札幌', departure: '22:32' },
      { station: '札幌', arrival: '22:41' },
    ],
  },
  {
    name: '3973M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '22:09' },
      { station: '千歳', departure: '22:13' },
      { station: '恵庭', departure: '22:19' },
      { station: '北広島', arrival: '22:26', departure: '22:26' },
      { station: '新札幌', departure: '22:35' },
      { station: '白石', departure: '22:41' },
      { station: '札幌', arrival: '22:47' },
    ],
  },
  {
    name: '3975M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '22:20' },
      { station: '千歳', departure: '22:24' },
      { station: '恵庭', departure: '22:29' },
      { station: '北広島', arrival: '22:37', departure: '22:37' },
      { station: '新札幌', departure: '22:45' },
      { station: '白石', departure: '22:51' },
      { station: '札幌', arrival: '22:57' },
    ],
  },
  {
    name: '4012D',
    type: 'おおぞら',
    schedules: [
      { station: '南千歳', departure: '22:28' },
      { station: '新札幌', departure: '22:49' },
      { station: '札幌', arrival: '22:59' },
    ],
  },
  {
    name: '3977M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '22:40' },
      { station: '千歳', departure: '22:44' },
      { station: '恵庭', departure: '22:50' },
      { station: '北広島', arrival: '22:57', departure: '22:57' },
      { station: '新札幌', departure: '23:06' },
      { station: '白石', departure: '23:11' },
      { station: '札幌', arrival: '23:17' },
    ],
  },
  {
    name: '2821M',
    type: '普通',
    schedules: [
      { station: '南千歳', departure: '22:46' },
      { station: '千歳', departure: '22:50' },
      { station: '長都', departure: '22:54' },
      { station: 'サッポロビール庭園', departure: '22:57' },
      { station: '恵庭', departure: '23:00' },
      { station: '恵み野', departure: '23:03' },
      { station: '島松', departure: '23:05' },
      { station: '北広島', arrival: '23:10', departure: '23:16' },
      { station: '上野幌', departure: '23:22' },
      { station: '新札幌', departure: '23:26' },
      { station: '平和', departure: '23:29' },
      { station: '白石', departure: '23:32' },
      { station: '苗穂', departure: '23:37' },
      { station: '札幌', arrival: '23:40' },
    ],
  },
  {
    name: '3979M',
    type: 'エアポート',
    schedules: [
      { station: '南千歳', departure: '22:56' },
      { station: '千歳', departure: '23:00' },
      { station: '恵庭', departure: '23:05' },
      { station: '北広島', arrival: '23:12', departure: '23:13' },
      { station: '新札幌', departure: '23:21' },
      { station: '白石', departure: '23:26' },
      { station: '札幌', arrival: '23:32' },
    ],
  },
  {
    name: '1823M',
    type: '普通',
    schedules: [
      { station: '千歳', departure: '23:11' },
      { station: '長都', departure: '23:15' },
      { station: 'サッポロビール庭園', departure: '23:18' },
      { station: '恵庭', departure: '23:21' },
      { station: '恵み野', departure: '23:23' },
      { station: '島松', departure: '23:26' },
      { station: '北広島', arrival: '23:31', departure: '23:31' },
      { station: '上野幌', departure: '23:37' },
      { station: '新札幌', departure: '23:41' },
      { station: '平和', departure: '23:44' },
      { station: '白石', departure: '23:47' },
      { station: '苗穂', departure: '23:51' },
      { station: '札幌', arrival: '23:54' },
    ],
  },
];

export const Page: NextPage = () => {
  return (
    <div>
      <DiagramFigure stations={stations} trains={trains} />
    </div>
  );
};

export default Page;
